# Generated by Django 4.0.6 on 2022-07-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0003_aprendiz_fecha_nacimeinto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprendiz',
            old_name='fecha_nacimeinto',
            new_name='fecha_nacimiento',
        ),
    ]
